#!/usr/bin/env python3
"""
Agency OS v5.0 — Output Formatter

Transforms raw AI text output into structured, professional deliverables:
- Per-studio output schemas
- Template-based report rendering
- Action item extraction
- Format conversion (MD → HTML, JSON → CSV)
"""

from __future__ import annotations

import csv
import io
import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger("agency.output")


@dataclass
class FormattedOutput:
    """Structured, formatted output from a studio."""

    raw: str = ""
    formatted: str = ""
    format_type: str = "markdown"  # markdown | html | json | csv
    action_items: list[dict[str, str]] = field(default_factory=list)
    sections: list[dict[str, str]] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    studio: str = ""
    quality_notes: list[str] = field(default_factory=list)


# Output schemas: what each studio should produce
STUDIO_SCHEMAS: dict[str, dict[str, Any]] = {
    "dev": {
        "required_sections": ["Summary", "Implementation", "Testing"],
        "optional_sections": ["Architecture", "Next Steps"],
        "should_contain": ["code block", "technical details"],
        "max_length": 5000,
    },
    "marketing": {
        "required_sections": ["Objective", "Target Audience", "Strategy"],
        "optional_sections": ["Budget", "Timeline", "KPIs"],
        "should_contain": ["audience", "messaging"],
        "max_length": 3000,
    },
    "sales": {
        "required_sections": ["Prospect", "Value Proposition", "Next Steps"],
        "optional_sections": ["Objections", "Competitor Analysis"],
        "should_contain": ["call to action"],
        "max_length": 2000,
    },
    "leadops": {
        "required_sections": ["Leads Found", "Qualification", "Actions"],
        "optional_sections": ["Scoring", "Sources"],
        "should_contain": ["contact", "qualified"],
        "max_length": 3000,
    },
    "analytics": {
        "required_sections": ["Summary", "Key Metrics", "Insights"],
        "optional_sections": ["Trends", "Recommendations"],
        "should_contain": ["data", "numbers"],
        "max_length": 4000,
    },
    "creative": {
        "required_sections": ["Concept", "Deliverables", "Timeline"],
        "optional_sections": ["Brand Guidelines", "Revisions"],
        "should_contain": ["visual", "brand"],
        "max_length": 2000,
    },
    "abm": {
        "required_sections": ["Target Account", "Personalization", "Channels"],
        "optional_sections": ["Timeline", "Budget"],
        "should_contain": ["account", "personalized"],
        "max_length": 3000,
    },
}

# Report templates
REPORT_TEMPLATES: dict[str, str] = {
    "executive_summary": """# {title}
**Date:** {date}
**Studio:** {studio}
**Status:** {status}

## Executive Summary
{summary}

## Key Findings
{findings}

## Recommendations
{recommendations}

## Next Steps
{next_steps}

---
*Generated by Agency OS v5.0*
""",
    "task_report": """# Task Report: {title}
**Completed:** {date} | **Duration:** {duration} | **Quality:** {quality}%

## Result
{content}

## Actions
{actions}

---
*Agency OS — {studio} Studio*
""",
    "pipeline_report": """# Pipeline Report
**Period:** {period} | **Studio:** {studio}

## Metrics
| Metric | Value |
|--------|-------|
{metrics_table}

## Activity
{activity}

## Issues & Recommendations
{issues}
""",
}


class OutputFormatter:
    """
    Transforms raw AI output into structured deliverables.

    Features:
    - Parse and validate against studio schemas
    - Extract action items from text
    - Apply report templates
    - Convert between formats (MD → HTML, JSON → CSV)
    """

    def __init__(self) -> None:
        self._schemas = dict(STUDIO_SCHEMAS)
        self._templates = dict(REPORT_TEMPLATES)

    def format(
        self,
        raw_output: str,
        studio: str = "dev",
        format_type: str = "markdown",
        title: str = "",
    ) -> FormattedOutput:
        """Format raw AI output into structured deliverable."""
        result = FormattedOutput(
            raw=raw_output,
            studio=studio,
            format_type=format_type,
        )

        # Extract sections
        result.sections = self._extract_sections(raw_output)

        # Extract action items
        result.action_items = self._extract_action_items(raw_output)

        # Validate against schema
        schema = self._schemas.get(studio)
        if schema:
            result.quality_notes = self._validate_schema(
                raw_output, result.sections, schema
            )

        # Apply formatting
        if format_type == "html":
            result.formatted = self._to_html(raw_output, title)
        elif format_type == "json":
            result.formatted = self._to_json(raw_output, result)
        elif format_type == "csv" and result.action_items:
            result.formatted = self._actions_to_csv(result.action_items)
        else:
            result.formatted = raw_output

        result.metadata = {
            "sections_found": len(result.sections),
            "action_items": len(result.action_items),
            "quality_notes": len(result.quality_notes),
            "char_count": len(raw_output),
            "word_count": len(raw_output.split()),
        }

        return result

    def render_report(
        self,
        template_name: str,
        variables: dict[str, str],
    ) -> str:
        """Render a report from a template."""
        template = self._templates.get(template_name)
        if not template:
            return f"Template not found: {template_name}"

        # Add default variables
        variables.setdefault("date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
        variables.setdefault("status", "Complete")

        result = template
        for key, val in variables.items():
            result = result.replace(f"{{{key}}}", str(val))

        return result

    # ── Extraction ───────────────────────────────────────────

    def _extract_sections(self, text: str) -> list[dict[str, str]]:
        """Extract markdown sections from text."""
        sections = []
        current_title = ""
        current_content: list[str] = []

        for line in text.split("\n"):
            if line.startswith("#"):
                if current_title:
                    sections.append(
                        {
                            "title": current_title,
                            "content": "\n".join(current_content).strip(),
                        }
                    )
                current_title = line.lstrip("#").strip()
                current_content = []
            else:
                current_content.append(line)

        if current_title:
            sections.append(
                {
                    "title": current_title,
                    "content": "\n".join(current_content).strip(),
                }
            )

        return sections

    def _extract_action_items(self, text: str) -> list[dict[str, str]]:
        """Extract action items, TODOs, and next steps from text."""
        actions = []

        patterns = [
            (r"[-*]\s*\[[ x]\]\s*(.+)", "todo"),
            (r"(?:TODO|FIXME|ACTION|NEXT):\s*(.+)", "action"),
            (r"(?:^|\n)\d+\.\s+(.+(?:should|must|need|will).+)", "recommendation"),
            (r"→\s*(.+)", "next_step"),
        ]

        for pattern, action_type in patterns:
            for match in re.finditer(pattern, text, re.IGNORECASE | re.MULTILINE):
                actions.append(
                    {
                        "text": match.group(1).strip()[:200],
                        "type": action_type,
                        "completed": "[x]" in match.group(0).lower(),
                    }
                )

        return actions  # type: ignore

    # ── Schema Validation ────────────────────────────────────

    def _validate_schema(
        self, text: str, sections: list[dict], schema: dict
    ) -> list[str]:
        """Validate output against studio schema."""
        notes = []
        text_lower = text.lower()
        section_titles = [s["title"].lower() for s in sections]

        # Check required sections
        for req in schema.get("required_sections", []):
            if not any(req.lower() in t for t in section_titles):
                notes.append(f"Missing required section: {req}")

        # Check content
        for keyword in schema.get("should_contain", []):
            if keyword.lower() not in text_lower:
                notes.append(f"Missing expected content: '{keyword}'")

        # Check length
        max_length = schema.get("max_length", 5000)
        if len(text) > max_length:
            notes.append(f"Output exceeds max length ({len(text)} > {max_length})")

        return notes

    # ── Format Converters ────────────────────────────────────

    def _to_html(self, markdown: str, title: str = "") -> str:
        """Convert Markdown to basic HTML."""
        html = markdown
        # Headers
        html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
        html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
        html = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)
        # Bold/italic
        html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
        html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)
        # Code blocks
        html = re.sub(
            r"```(\w+)?\n(.*?)```", r"<pre><code>\2</code></pre>", html, flags=re.DOTALL
        )
        html = re.sub(r"`(.+?)`", r"<code>\1</code>", html)
        # Lists
        html = re.sub(r"^[-*] (.+)$", r"<li>\1</li>", html, flags=re.MULTILINE)
        # Paragraphs
        html = re.sub(r"\n\n", "</p>\n<p>", html)
        # Links
        html = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', html)

        return f"""<!DOCTYPE html>
<html><head><title>{title or "Agency OS Report"}</title>
<style>body{{font-family:system-ui;max-width:800px;margin:2rem auto;padding:0 1rem;line-height:1.6}}
code{{background:#f4f4f4;padding:2px 6px;border-radius:3px}}
pre code{{display:block;padding:1rem;overflow-x:auto}}</style>
</head><body><p>{html}</p></body></html>"""

    def _to_json(self, text: str, output: FormattedOutput) -> str:
        """Convert output to structured JSON."""
        return json.dumps(
            {
                "content": text,
                "sections": output.sections,
                "action_items": output.action_items,
                "metadata": output.metadata,
            },
            indent=2,
            ensure_ascii=False,
        )

    def _actions_to_csv(self, actions: list[dict]) -> str:
        """Convert action items to CSV."""
        buf = io.StringIO()
        writer = csv.DictWriter(buf, fieldnames=["text", "type", "completed"])
        writer.writeheader()
        writer.writerows(actions)
        return buf.getvalue()

    # ── Stats ────────────────────────────────────────────────

    def list_schemas(self) -> dict[str, list[str]]:
        return {
            studio: schema["required_sections"]
            for studio, schema in self._schemas.items()
        }

    def list_templates(self) -> list[str]:
        return list(self._templates.keys())


_formatter: OutputFormatter | None = None


def get_output_formatter() -> OutputFormatter:
    global _formatter
    if _formatter is None:
        _formatter = OutputFormatter()
    return _formatter
